### ISSUE TITLE
Links de estudo para CSS

### ISSUE THREAD

**Issue by guissalustiano** [React-Avancado/links-estudo#13]
Boa tarde!
Seria possivel adicionar links bons para se estudar css?

Eu conheço uns poucos como:
https://css-tricks.com/guides/
https://developer.mozilla.org/en-US/docs/Web/CSS

Adoraria um também sobre efeitos mais conhecidos, como paralex, e outros que o will cita no curso como o shimerim efect (n sei se escrevi certo, mas é o que faz a imagem carregar aos poucos)

Obrigado!

**Comment by willianjusten** [comment]
Cria um PR com os links =)

Eu gosto bastante do https://tympanus.net/codrops/ , lá tem muitos efeitos avançados.
